remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: contrast


title: Aiden Van Greuning
description: Biomedical Engineering Portfolio

url: "https://aiden-vangreuning.github.io"
baseurl: "/aiden-vangreuning"

google_analytics: G-6XDVHZK5TM

plugins:
  - jekyll-include-cache

atom_feed:
  hide: true

# Disable blog functionality
paginate: false
search: false
breadcrumbs: false
comments: false

defaults:
  - scope:
      path: ""
    values:
      layout: page
